steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/high-torch-329323/demo-flask-app', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/high-torch-329323/demo-flask-app']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'demo-flask-app', '--image', 'gcr.io/high-torch-329323/demo-flask-app', '--region', 'us-west1', '--platform', 'managed', '--port', '80']
images:
- gcr.io/high-torch-329323/demo-flask-app